package app.yarn.intelligence

/**
 * Turns business sender IDs like "AD-HDFCBK-S" into readable names ("HDFC Bank").
 * Unknown IDs fall back to their brand part ("VM-ACMEIN-T" -> "ACMEIN").
 */
object SenderNames {
    private class Brand(val prefix: Regex, val name: String, val category: Category)

    private val KNOWN: List<Brand> = listOf(
        // More specific prefixes first (JIOMRT before JIO, BSES before BSE, LICIOS before LIC...).
        Brand(Regex("^JIOMRT"), "JioMart", Category.SHOPPING),
        Brand(Regex("^JIOMART"), "JioMart", Category.SHOPPING),
        Brand(Regex("^AIRBNK"), "Airtel Payments Bank", Category.BANKING),
        Brand(Regex("^ARTLPB"), "Airtel Payments Bank", Category.BANKING),
        Brand(Regex("^AIRPAY"), "Airtel Payments Bank", Category.BANKING),
        Brand(Regex("^LICIOS"), "Licious", Category.SHOPPING),
        Brand(Regex("^LICIUS"), "Licious", Category.SHOPPING),
        Brand(Regex("^BSES"), "BSES", Category.BILLS),
        Brand(Regex("^HDFC"), "HDFC Bank", Category.BANKING),
        Brand(Regex("^ICICI"), "ICICI Bank", Category.BANKING),
        Brand(Regex("^ATMSBI"), "SBI", Category.BANKING),
        Brand(Regex("^CBSSBI"), "SBI", Category.BANKING),
        Brand(Regex("^SBICRD"), "SBI Card", Category.BANKING),
        Brand(Regex("^SBI"), "SBI", Category.BANKING),
        Brand(Regex("^AXIS"), "Axis Bank", Category.BANKING),
        Brand(Regex("^KOTAK"), "Kotak Bank", Category.BANKING),
        Brand(Regex("^BOBCRD"), "Bob Card", Category.BANKING),
        Brand(Regex("^BOB"), "Bank of Baroda", Category.BANKING),
        Brand(Regex("^PNB"), "PNB", Category.BANKING),
        Brand(Regex("^CANBNK"), "Canara Bank", Category.BANKING),
        Brand(Regex("^CANARA"), "Canara Bank", Category.BANKING),
        Brand(Regex("^UNIONB"), "Union Bank", Category.BANKING),
        Brand(Regex("^UBOI"), "Union Bank", Category.BANKING),
        Brand(Regex("^IDFC"), "IDFC FIRST Bank", Category.BANKING),
        Brand(Regex("^YESB"), "Yes Bank", Category.BANKING),
        Brand(Regex("^INDUS"), "IndusInd Bank", Category.BANKING),
        Brand(Regex("^IDBI"), "IDBI Bank", Category.BANKING),
        Brand(Regex("^FEDBNK"), "Federal Bank", Category.BANKING),
        Brand(Regex("^FEDERL"), "Federal Bank", Category.BANKING),
        Brand(Regex("^AUBANK"), "AU Bank", Category.BANKING),
        Brand(Regex("^RBLBNK"), "RBL Bank", Category.BANKING),
        Brand(Regex("^RBLCRD"), "RBL Bank", Category.BANKING),
        Brand(Regex("^BANDHN"), "Bandhan Bank", Category.BANKING),
        Brand(Regex("^DBSBNK"), "DBS Bank", Category.BANKING),
        Brand(Regex("^HSBC"), "HSBC", Category.BANKING),
        Brand(Regex("^SCBANK"), "Standard Chartered", Category.BANKING),
        Brand(Regex("^STANCB"), "Standard Chartered", Category.BANKING),
        Brand(Regex("^CITI"), "Citi", Category.BANKING),
        Brand(Regex("^AMEX"), "American Express", Category.BANKING),
        Brand(Regex("^IOB"), "Indian Overseas Bank", Category.BANKING),
        Brand(Regex("^CENTBK"), "Central Bank", Category.BANKING),
        Brand(Regex("^BOIIND"), "Bank of India", Category.BANKING),
        Brand(Regex("^BOISMS"), "Bank of India", Category.BANKING),
        Brand(Regex("^UCOBNK"), "UCO Bank", Category.BANKING),
        Brand(Regex("^INDBNK"), "Indian Bank", Category.BANKING),
        Brand(Regex("^MAHABK"), "Bank of Maharashtra", Category.BANKING),
        Brand(Regex("^KVBANK"), "Karur Vysya Bank", Category.BANKING),
        Brand(Regex("^CUBANK"), "City Union Bank", Category.BANKING),
        Brand(Regex("^SIBSMS"), "South Indian Bank", Category.BANKING),
        Brand(Regex("^KARBNK"), "Karnataka Bank", Category.BANKING),
        Brand(Regex("^EQUTAS"), "Equitas Bank", Category.BANKING),
        Brand(Regex("^UJJIVN"), "Ujjivan Bank", Category.BANKING),
        Brand(Regex("^JKBANK"), "J&K Bank", Category.BANKING),
        Brand(Regex("^DCBBNK"), "DCB Bank", Category.BANKING),
        Brand(Regex("^SRSWAT"), "Saraswat Bank", Category.BANKING),
        Brand(Regex("^PAYTMB"), "Paytm Payments Bank", Category.BANKING),
        Brand(Regex("^IPPB"), "India Post Payments Bank", Category.BANKING),
        Brand(Regex("^FINOBK"), "Fino Bank", Category.BANKING),
        Brand(Regex("^ONECRD"), "OneCard", Category.BANKING),
        Brand(Regex("^SLICE"), "slice", Category.BANKING),
        Brand(Regex("^JUPITR"), "Jupiter", Category.BANKING),
        Brand(Regex("^FIMONY"), "Fi", Category.BANKING),
        Brand(Regex("^NIYO"), "Niyo", Category.BANKING),
        Brand(Regex("^UNICRD"), "Uni Cards", Category.BANKING),
        Brand(Regex("^CDSL"), "CDSL", Category.BANKING),
        Brand(Regex("^NSDL"), "NSDL", Category.BANKING),
        Brand(Regex("^ZERODH"), "Zerodha", Category.BANKING),
        Brand(Regex("^GROWW"), "Groww", Category.BANKING),
        Brand(Regex("^UPSTOX"), "Upstox", Category.BANKING),
        Brand(Regex("^ANGEL"), "Angel One", Category.BANKING),
        Brand(Regex("^SHRKHN"), "Sharekhan", Category.BANKING),
        Brand(Regex("^KFIN"), "KFintech", Category.BANKING),
        Brand(Regex("^CAMS"), "CAMS", Category.BANKING),
        Brand(Regex("^MFCNTL"), "MF Central", Category.BANKING),
        Brand(Regex("^BSELTD"), "BSE", Category.BANKING),
        Brand(Regex("^BSE"), "BSE", Category.BANKING),
        Brand(Regex("^NSEIND"), "NSE", Category.BANKING),
        Brand(Regex("^NSE"), "NSE", Category.BANKING),
        Brand(Regex("^NPSCRA"), "NPS", Category.BANKING),
        Brand(Regex("^BAJAJF"), "Bajaj Finserv", Category.BANKING),
        Brand(Regex("^BAJFIN"), "Bajaj Finserv", Category.BANKING),
        Brand(Regex("^HDBFS"), "HDB Financial", Category.BANKING),
        Brand(Regex("^TATCAP"), "Tata Capital", Category.BANKING),
        Brand(Regex("^TATACP"), "Tata Capital", Category.BANKING),
        Brand(Regex("^MUTHOO"), "Muthoot Finance", Category.BANKING),
        Brand(Regex("^MANAPM"), "Manappuram", Category.BANKING),
        Brand(Regex("^LNTFIN"), "L&T Finance", Category.BANKING),
        Brand(Regex("^KREDTB"), "KreditBee", Category.BANKING),
        Brand(Regex("^MNYVIW"), "Moneyview", Category.BANKING),
        Brand(Regex("^NAVI"), "Navi", Category.BANKING),
        Brand(Regex("^LICIND"), "LIC", Category.BILLS),
        Brand(Regex("^LICHFL"), "LIC Housing Finance", Category.BANKING),
        Brand(Regex("^MAXLIF"), "Max Life", Category.BILLS),
        Brand(Regex("^STARHL"), "Star Health", Category.BILLS),
        Brand(Regex("^ACKO"), "ACKO", Category.BILLS),
        Brand(Regex("^GODIGT"), "Digit Insurance", Category.BILLS),
        Brand(Regex("^PLCYBZ"), "Policybazaar", Category.BILLS),
        Brand(Regex("^POLBZR"), "Policybazaar", Category.BILLS),
        Brand(Regex("^PAYTM"), "Paytm", Category.PAYMENTS),
        Brand(Regex("^PHONPE"), "PhonePe", Category.PAYMENTS),
        Brand(Regex("^PHONEPE"), "PhonePe", Category.PAYMENTS),
        Brand(Regex("^GPAY"), "Google Pay", Category.PAYMENTS),
        Brand(Regex("^GOOGPY"), "Google Pay", Category.PAYMENTS),
        Brand(Regex("^CRED"), "CRED", Category.PAYMENTS),
        Brand(Regex("^MOBIKW"), "MobiKwik", Category.PAYMENTS),
        Brand(Regex("^AMZPAY"), "Amazon Pay", Category.PAYMENTS),
        Brand(Regex("^APAYIN"), "Amazon Pay", Category.PAYMENTS),
        Brand(Regex("^FRCHRG"), "Freecharge", Category.PAYMENTS),
        Brand(Regex("^BHIM"), "BHIM", Category.PAYMENTS),
        Brand(Regex("^NPCI"), "NPCI", Category.PAYMENTS),
        Brand(Regex("^SIMPL"), "Simpl", Category.PAYMENTS),
        Brand(Regex("^LZYPAY"), "LazyPay", Category.PAYMENTS),
        Brand(Regex("^RAZRPY"), "Razorpay", Category.PAYMENTS),
        Brand(Regex("^PAYU"), "PayU", Category.PAYMENTS),
        Brand(Regex("^CASHFR"), "Cashfree", Category.PAYMENTS),
        Brand(Regex("^FASTAG"), "FASTag", Category.PAYMENTS),
        Brand(Regex("^NETCFT"), "FASTag", Category.PAYMENTS),
        Brand(Regex("^AMAZON"), "Amazon", Category.SHOPPING),
        Brand(Regex("^AMZN"), "Amazon", Category.SHOPPING),
        Brand(Regex("^FLPKRT"), "Flipkart", Category.SHOPPING),
        Brand(Regex("^FLIPKT"), "Flipkart", Category.SHOPPING),
        Brand(Regex("^FLIPKR"), "Flipkart", Category.SHOPPING),
        Brand(Regex("^SHOPSY"), "Shopsy", Category.SHOPPING),
        Brand(Regex("^MYNTRA"), "Myntra", Category.SHOPPING),
        Brand(Regex("^AJIO"), "AJIO", Category.SHOPPING),
        Brand(Regex("^MEESHO"), "Meesho", Category.SHOPPING),
        Brand(Regex("^NYKAA"), "Nykaa", Category.SHOPPING),
        Brand(Regex("^PURPLL"), "Purplle", Category.SHOPPING),
        Brand(Regex("^TATACQ"), "Tata CLiQ", Category.SHOPPING),
        Brand(Regex("^TCLIQ"), "Tata CLiQ", Category.SHOPPING),
        Brand(Regex("^TATANU"), "Tata Neu", Category.SHOPPING),
        Brand(Regex("^RELDIG"), "Reliance Digital", Category.SHOPPING),
        Brand(Regex("^CROMA"), "Croma", Category.SHOPPING),
        Brand(Regex("^VIJAYS"), "Vijay Sales", Category.SHOPPING),
        Brand(Regex("^DMART"), "DMart", Category.SHOPPING),
        Brand(Regex("^LENSKT"), "Lenskart", Category.SHOPPING),
        Brand(Regex("^FCRY"), "FirstCry", Category.SHOPPING),
        Brand(Regex("^FIRSTC"), "FirstCry", Category.SHOPPING),
        Brand(Regex("^BEWAKO"), "Bewakoof", Category.SHOPPING),
        Brand(Regex("^SNAPDL"), "Snapdeal", Category.SHOPPING),
        Brand(Regex("^PEPRFR"), "Pepperfry", Category.SHOPPING),
        Brand(Regex("^IKEA"), "IKEA", Category.SHOPPING),
        Brand(Regex("^DECATH"), "Decathlon", Category.SHOPPING),
        Brand(Regex("^BOATLF"), "boAt", Category.SHOPPING),
        Brand(Regex("^BLINKT"), "Blinkit", Category.SHOPPING),
        Brand(Regex("^BLNKIT"), "Blinkit", Category.SHOPPING),
        Brand(Regex("^BLINKI"), "Blinkit", Category.SHOPPING),
        Brand(Regex("^ZEPTO"), "Zepto", Category.SHOPPING),
        Brand(Regex("^BIGBSK"), "bigbasket", Category.SHOPPING),
        Brand(Regex("^BBASKT"), "bigbasket", Category.SHOPPING),
        Brand(Regex("^BBDALY"), "bb daily", Category.SHOPPING),
        Brand(Regex("^SWIGGY"), "Swiggy", Category.SHOPPING),
        Brand(Regex("^ZOMATO"), "Zomato", Category.SHOPPING),
        Brand(Regex("^DUNZO"), "Dunzo", Category.SHOPPING),
        Brand(Regex("^EATSUR"), "EatSure", Category.SHOPPING),
        Brand(Regex("^DOMINO"), "Domino's", Category.SHOPPING),
        Brand(Regex("^PIZZAH"), "Pizza Hut", Category.SHOPPING),
        Brand(Regex("^MCDIND"), "McDonald's", Category.SHOPPING),
        Brand(Regex("^KFCIND"), "KFC", Category.SHOPPING),
        Brand(Regex("^FRSHTH"), "FreshToHome", Category.SHOPPING),
        Brand(Regex("^CNTRYD"), "Country Delight", Category.SHOPPING),
        Brand(Regex("^MLKBSK"), "Milkbasket", Category.SHOPPING),
        Brand(Regex("^PHRMS"), "PharmEasy", Category.SHOPPING),
        Brand(Regex("^PHARME"), "PharmEasy", Category.SHOPPING),
        Brand(Regex("^ONEMG"), "Tata 1mg", Category.SHOPPING),
        Brand(Regex("^TATA1M"), "Tata 1mg", Category.SHOPPING),
        Brand(Regex("^1MG"), "Tata 1mg", Category.SHOPPING),
        Brand(Regex("^NETMED"), "Netmeds", Category.SHOPPING),
        Brand(Regex("^MEDPLS"), "MedPlus", Category.SHOPPING),
        Brand(Regex("^DLHVRY"), "Delhivery", Category.DELIVERY),
        Brand(Regex("^DELHIV"), "Delhivery", Category.DELIVERY),
        Brand(Regex("^BLUDRT"), "Blue Dart", Category.DELIVERY),
        Brand(Regex("^BLUEDT"), "Blue Dart", Category.DELIVERY),
        Brand(Regex("^EKART"), "Ekart", Category.DELIVERY),
        Brand(Regex("^ECOMEX"), "Ecom Express", Category.DELIVERY),
        Brand(Regex("^ECMEXP"), "Ecom Express", Category.DELIVERY),
        Brand(Regex("^XPRSBS"), "XpressBees", Category.DELIVERY),
        Brand(Regex("^XPRESB"), "XpressBees", Category.DELIVERY),
        Brand(Regex("^SHDWFX"), "Shadowfax", Category.DELIVERY),
        Brand(Regex("^SHADOW"), "Shadowfax", Category.DELIVERY),
        Brand(Regex("^DTDC"), "DTDC", Category.DELIVERY),
        Brand(Regex("^INDPST"), "India Post", Category.DELIVERY),
        Brand(Regex("^INPOST"), "India Post", Category.DELIVERY),
        Brand(Regex("^SHPRKT"), "Shiprocket", Category.DELIVERY),
        Brand(Regex("^SMRTR"), "Smartr", Category.DELIVERY),
        Brand(Regex("^PORTER"), "Porter", Category.DELIVERY),
        Brand(Regex("^UBER"), "Uber", Category.TRAVEL),
        Brand(Regex("^OLA"), "Ola", Category.TRAVEL),
        Brand(Regex("^RAPIDO"), "Rapido", Category.TRAVEL),
        Brand(Regex("^IRCTC"), "IRCTC", Category.TRAVEL),
        Brand(Regex("^INDIGO"), "IndiGo", Category.TRAVEL),
        Brand(Regex("^GOINDG"), "IndiGo", Category.TRAVEL),
        Brand(Regex("^AIRIND"), "Air India", Category.TRAVEL),
        Brand(Regex("^AIXPRS"), "Air India Express", Category.TRAVEL),
        Brand(Regex("^VISTAR"), "Vistara", Category.TRAVEL),
        Brand(Regex("^AKASA"), "Akasa Air", Category.TRAVEL),
        Brand(Regex("^SPICEJ"), "SpiceJet", Category.TRAVEL),
        Brand(Regex("^MMTRIP"), "MakeMyTrip", Category.TRAVEL),
        Brand(Regex("^GOIBIB"), "Goibibo", Category.TRAVEL),
        Brand(Regex("^CLRTRP"), "Cleartrip", Category.TRAVEL),
        Brand(Regex("^YATRA"), "Yatra", Category.TRAVEL),
        Brand(Regex("^EASEMT"), "EaseMyTrip", Category.TRAVEL),
        Brand(Regex("^IXIGO"), "ixigo", Category.TRAVEL),
        Brand(Regex("^REDBUS"), "redBus", Category.TRAVEL),
        Brand(Regex("^ABHIBS"), "AbhiBus", Category.TRAVEL),
        Brand(Regex("^OYO"), "OYO", Category.TRAVEL),
        Brand(Regex("^BMSHOW"), "BookMyShow", Category.UPDATES),
        Brand(Regex("^BKMYSH"), "BookMyShow", Category.UPDATES),
        Brand(Regex("^BESCOM"), "BESCOM", Category.BILLS),
        Brand(Regex("^TATAPW"), "Tata Power", Category.BILLS),
        Brand(Regex("^ADANIE"), "Adani Electricity", Category.BILLS),
        Brand(Regex("^MSEDCL"), "MSEDCL", Category.BILLS),
        Brand(Regex("^MAHADS"), "MSEDCL", Category.BILLS),
        Brand(Regex("^TNEB"), "TNEB", Category.BILLS),
        Brand(Regex("^TANGED"), "TANGEDCO", Category.BILLS),
        Brand(Regex("^KSEB"), "KSEB", Category.BILLS),
        Brand(Regex("^CESC"), "CESC", Category.BILLS),
        Brand(Regex("^TORNTP"), "Torrent Power", Category.BILLS),
        Brand(Regex("^IGLSMS"), "IGL", Category.BILLS),
        Brand(Regex("^MGLTD"), "Mahanagar Gas", Category.BILLS),
        Brand(Regex("^INDANE"), "Indane Gas", Category.BILLS),
        Brand(Regex("^HPGAS"), "HP Gas", Category.BILLS),
        Brand(Regex("^BPCL"), "Bharat Gas", Category.BILLS),
        Brand(Regex("^ACTFBR"), "ACT Fibernet", Category.BILLS),
        Brand(Regex("^HATHWY"), "Hathway", Category.BILLS),
        Brand(Regex("^TTPLAY"), "Tata Play", Category.BILLS),
        Brand(Regex("^DISHTV"), "Dish TV", Category.BILLS),
        Brand(Regex("^JIO"), "Jio", Category.UPDATES),
        Brand(Regex("^AIRTEL"), "Airtel", Category.UPDATES),
        Brand(Regex("^VIL"), "Vi", Category.UPDATES),
        Brand(Regex("^VFCARE"), "Vi", Category.UPDATES),
        Brand(Regex("^VICARE"), "Vi", Category.UPDATES),
        Brand(Regex("^BSNL"), "BSNL", Category.UPDATES),
        Brand(Regex("^MTNL"), "MTNL", Category.UPDATES),
        Brand(Regex("^UIDAI"), "UIDAI (Aadhaar)", Category.UPDATES),
        Brand(Regex("^EPFO"), "EPFO", Category.UPDATES),
        Brand(Regex("^ITDEPT"), "Income Tax Dept", Category.UPDATES),
        Brand(Regex("^GSTIND"), "GST", Category.UPDATES),
        Brand(Regex("^DIGILK"), "DigiLocker", Category.UPDATES),
        Brand(Regex("^MYGOV"), "MyGov", Category.UPDATES),
        Brand(Regex("^PARIVH"), "Parivahan", Category.UPDATES),
        Brand(Regex("^VAHAN"), "Parivahan", Category.UPDATES),
        Brand(Regex("^COWIN"), "CoWIN", Category.UPDATES),
        Brand(Regex("^GOOGLE"), "Google", Category.UPDATES),
        Brand(Regex("^WHATSP"), "WhatsApp", Category.UPDATES),
        Brand(Regex("^NETFLX"), "Netflix", Category.UPDATES),
        Brand(Regex("^HOTSTR"), "Hotstar", Category.UPDATES),
        Brand(Regex("^SPOTFY"), "Spotify", Category.UPDATES),
        Brand(Regex("^APOLLO"), "Apollo", Category.UPDATES),
        Brand(Regex("^PRACTO"), "Practo", Category.UPDATES),
        Brand(Regex("^URBNCO"), "Urban Company", Category.UPDATES),
        Brand(Regex("^URBANC"), "Urban Company", Category.UPDATES),
    )

    fun isBusiness(address: String): Boolean {
        val a = address.trim()
        if (a.contains('@')) return false
        return a.any { it.isLetter() } || a.filter { it.isDigit() }.length in 3..8 && !a.startsWith("+")
    }

    /** Readable name for an alphanumeric sender, or null when [address] isn't one. */
    fun pretty(address: String): String? {
        val a = address.trim()
        if (a.contains('@') || a.none { it.isLetter() }) return null
        val brand = SenderAnalyzer.brandToken(a)
        return KNOWN.firstOrNull { it.prefix.containsMatchIn(brand) }?.name ?: brand
    }

    /** The usual category of a well-known business sender, used as a gentle prior. */
    fun brandCategory(address: String): Category? {
        val a = address.trim()
        if (a.contains('@') || a.none { it.isLetter() }) return null
        val brand = SenderAnalyzer.brandToken(a)
        return KNOWN.firstOrNull { it.prefix.containsMatchIn(brand) }?.category
    }
}
